### ISSUE TITLE
request: ability to disable prefetch

### ISSUE THREAD

**Issue by gavinsharp** [nodeca/promise-memoize#8]
Thanks for this library!

I am using this library in an AWS Lambda, and ran into an interesting bug caused by the prefetch behavior. My app has code that looks like this:
```
async function doGetCredentials() {
  // ...async retrieval of credentials that expire after 1 hour...
  return credentials;
}

// memoize credentials while they are valid
const getCredentials = promiseMemoize(doGetCredentials, { maxAge: credentialExpiryAge } );

getCredentials().then(doStuff).then(returnResponse);
```

The issue I encountered is that AWS Lambdas can be immediately paused (i.e. JS execution stops) as soon as a response is returned, and then re-animated later to handle future requests. This can lead to a scenario where:
1) request comes in, `doGetCredentials` is called and the result is memoized
1) another request comes when the memoized result is "almost expired", so the prefetch request is triggered, but the memoized value is returned.
1) my code returns a response without waiting for the prefetch request to complete, so Lambda execution is frozen. This happens after the credential request has been made, but before the doGetCredentials promise is fully resolved (i.e. before the refreshed value is memoized). 
1) another request comes in some time later, so Lambda execution resumes. finally the prefetch promise resolves, and the result is cached for `maxAge`. But the credentials being saved are from some time ago, so they could be already expired (or almost expired). Subsequent requests can get expired credentials.

I think the cleanest fix to this problem would be to just disable the prefetching behavior, so that my response always waits for the credential request to complete, and Lambda can't pause execution mid-way through the credential request.

**Comment by puzrin** [comment]
While implementation of prefetch disable is technically possible, i feel something deeply wrong about such approach. It looks like you try use this lib as storage, while it's for performance.

If you don't need prefetch - just keep credential + timestamp in local object and request new only when required:

```js
if (credsExpided) {
  newCreds = await getCreds();
}
```

If timers in your system are not trusted, correct implementation should use system timestamps for validation.

**Comment by gavinsharp** [comment]
Using this library "for storage" (as you describe it) seems perfectly reasonable to me, but that's a matter of opinion, and not really what this request is about :)

It didn't seem unreasonable to me to request the ability to disable the prefetch behavior, since it doesn't seem inherent to the purpose of the library. But of course that is for you to decide as a maintainer - if you don't want to add the feature I suppose I will just re-implement this myself or use another library (`p-memoize` seems like a reasonable alternative).

**Comment by puzrin** [comment]
Probably, my explanations were bad. I meaned, this library and the most of it's code size was done because correct implementation of prefetch required. So, option to disable it may look strange from this point of view.

Let's close issue, if you are ok to move forward in different way. Also, take a look at https://github.com/medikoo/memoizee - it should be more tunable (because more complicated internally).

**Comment by gavinsharp** [comment]
Makes sense. Thanks for the quick responses!

**Comment by jpbochi** [comment]
I'm sad this feature was not implemented. I'd like to use this lib because of GC, mostly. I'm also interested in caching the errors for a little while.

To clarify my case, the function to be memoized is called with large variety of keys. They come in waves of equal keys that might take a while to come back later. This means that GC is important, and prefetching is not.

**Comment by puzrin** [comment]
@jpbochi did you inspected code? IMHO GC will be ineffective for large keys variations. That's all because library was designed for medium variations but high repeat rates. If i had to implement GC only, i would do it different somehow.

**Comment by jpbochi** [comment]
@puzrin in my case, if I use a low `maxAge`, the amount of valid keys would be small.

But I did look at your code. Having one `setTimeout` for each key might be too expensive for my case. A single timer that performs some GC once in a while (or some other trick) would be better for what I need.

**Comment by puzrin** [comment]
That's exactly what i mean.

I use this module to cache usergroups permissions - variability is low, but requests rate is high and freezes (when cache expires) are not desired.

I could not find way to make GC & prefetch right simultaneously. If i promote "GC only" mode, the next request will be "your GC is ugly and should be improved" :).

**Comment by jpbochi** [comment]
I see what you mean. It's a fair point.
